version: "3.3"

services:
  faunadb:
    image: fauna/faunadb
    container_name: faunadb
    ports:
      - "8443:8443"

  node-lts:
    image: node:18.16-alpine3.16
    container_name: node-lts
    depends_on:
      - faunadb
    volumes:
      - "../../:/tmp/app"
    working_dir: "/tmp/app"
    environment:
      FAUNA_ENDPOINT: http://faunadb:8443
      FAUNA_SECRET: secret
    command:
      - /bin/sh
      - -cxe
      - |
        apk add --no-cache curl
        ./wait-for-it.sh http://faunadb:8443/ping
        yarn test:integration

  node-current:
    image: node:20.2-alpine3.16
    container_name: node-current
    depends_on:
      - faunadb
    volumes:
      - "../../:/tmp/app"
    working_dir: "/tmp/app"
    environment:
      FAUNA_ENDPOINT: http://faunadb:8443
      FAUNA_SECRET: secret
    command:
      - /bin/sh
      - -cxe
      - |
        apk add --no-cache curl
        ./wait-for-it.sh http://faunadb:8443/ping
        yarn test:integration
