version: "3.5"

networks:
  limit-net:
    external: true
    name: limit-net

services:
  faunadb:
    image: fauna/faunadb:4.28.0
    container_name: faunadb
    ports:
      - "8443:8443"

  node-lts:
    image: node:18.16-alpine3.16
    container_name: node-lts
    depends_on:
      - faunadb
    volumes:
      - "../../:/tmp/app"
    working_dir: "/tmp/app"
    environment:
      FAUNA_ENDPOINT: http://faunadb:8443
      FAUNA_SECRET: secret
    command:
      - /bin/sh
      - -cxe
      - |
        apk add --no-cache curl
        ./wait-for-it.sh http://faunadb:8443/ping
        yarn test:integration

  node-current:
    image: node:20.2-alpine3.16
    container_name: node-current
    depends_on:
      - faunadb
    volumes:
      - "../../:/tmp/app"
    working_dir: "/tmp/app"
    environment:
      FAUNA_ENDPOINT: http://faunadb:8443
      FAUNA_SECRET: secret
    command:
      - /bin/sh
      - -cxe
      - |
        apk add --no-cache curl
        ./wait-for-it.sh http://faunadb:8443/ping
        yarn test:integration

  query-limits-tests:
    image: node:20.2-alpine3.16
    container_name: node-current-limits-test
    networks:
      - limit-net
    volumes:
      - "../../:/tmp/app"
    working_dir: "/tmp/app"
    environment:
      FAUNA_ENDPOINT: ${FAUNA_ENDPOINT:-http://fauna-limits:8443}
      QUERY_LIMITS_DB: ${QUERY_LIMITS_DB}
      QUERY_LIMITS_COLL: ${QUERY_LIMITS_COLL}
    command:
      - /bin/sh
      - -cxe
      - |
        yarn test:query-limits
