---
resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

resources:
  - name: notify
    type: slack-notification
    icon: slack
    source:
      url: ((slack-webhook))

  - name: main.git
    type: git
    icon: github
    source:
      uri: git@github.com:fauna/fauna-js.git
      branch: main
      #      tag_filter: v*
      private_key: ((github-ssh-key))

  - name: testtools-repo
    type: git
    icon: github
    source:
      uri: git@github.com:fauna/testtools.git
      branch: main
      private_key: ((github-ssh-key))

  - name: testtools-image
    type: registry-image
    icon: docker
    source:
      repository: devex-dx-drivers-platform-tests
      aws_access_key_id: ((prod-images-aws-access-key-id))
      aws_secret_access_key: ((prod-images-aws-secret-key))
      aws_region: us-east-2

  - name: fauna-js-repository-docs
    type: git
    icon: github
    source:
      uri: git@github.com:fauna/fauna-js.git
      branch: gh-pages
      private_key: ((github-ssh-key))

groups:
  - name: pipeline
    jobs:
      - set-self
      - test
      - release

jobs:
  - name: set-self
    serial: true
    plan:
      - get: main.git
        trigger: true
      - set_pipeline: self
        file: main.git/concourse/pipeline.yml

  - name: test
    serial: true
    plan:
      - get: main.git
        passed:
          - set-self

      - get: testtools-repo
      - get: testtools-image

      - load_var: git-commit
        reveal: true
        file: main.git/.git/ref

      - in_parallel:
          fail_fast: false
          steps:
            - task: aws-lambda-tests
              image: testtools-image
              file: testtools-repo/fauna-driver-platform-tests/concourse/tasks/js-aws-lambda-tests.yml
              params:
                GIT_COMMIT: ((.:git-commit))
                FAUNA_SECRET: ((drivers-platform-tests/fauna-secret))
                AWS_LAMBDA_ROLE_ARN: ((drivers-platform-tests/aws-lambda-role-arn))
                AWS_ACCESS_KEY_ID: ((drivers-platform-tests/aws-access-key-id))
                AWS_SECRET_ACCESS_KEY: ((drivers-platform-tests/aws-secret-key))

            - task: cloudflare-tests
              image: testtools-image
              file: testtools-repo/fauna-driver-platform-tests/concourse/tasks/js-cloudflare-workers-tests.yml
              params:
                GIT_COMMIT: ((.:git-commit))
                CLOUDFLARE_API_TOKEN: ((drivers-platform-tests/cloudflare-api-token))
                FAUNA_SECRET: ((drivers-platform-tests/fauna-secret))
                VERCEL_TOKEN: ((drivers-platform-tests/vercel-token))

            - task: netlify-tests
              image: testtools-image
              file: testtools-repo/fauna-driver-platform-tests/concourse/tasks/js-netlify-tests.yml
              params:
                GIT_COMMIT: ((.:git-commit))
                FAUNA_SECRET: ((drivers-platform-tests/fauna-secret))
                NETLIFY_ACCOUNT: ((drivers-platform-tests/netlify-account))
                NETLIFY_AUTH_TOKEN: ((drivers-platform-tests/netlify-auth-token))

            - task: query-limits-tests
              privileged: true
              file: main.git/concourse/tasks/query-limits-tests.yml
              input_mapping:
                { repo.git: main.git, testtools-repo: testtools-repo }
              params:
                QUERY_LIMITS_DB: limited
                QUERY_LIMITS_COLL: limitCollection

            # - task: vercel-tests
            #   image: testtools-image
            #   file: testtools-repo/fauna-driver-platform-tests/concourse/tasks/js-vercel-tests.yml
            #   params:
            #     GIT_COMMIT: ((.:git-commit))
            #     FAUNA_SECRET: ((drivers-platform-tests/fauna-secret))
            #     VERCEL_TOKEN: ((drivers-platform-tests/vercel-token))

  - name: release
    serial: true
    public: false
    plan:
      - get: main.git
        passed:
          - test
      - get: fauna-js-repository-docs

      - task: integration-tests
        file: main.git/concourse/tasks/integration-tests.yml
        input_mapping: { repo.git: main.git }
        privileged: true
        on_success:
          put: notify
          params:
            text: "fauna-js driver release passed integration tests"
        on_failure:
          put: notify
          params:
            text: fauna-js driver release failed integration tests

      - task: publish
        file: main.git/concourse/tasks/npm-publish.yml
        input_mapping: { repo.git: main.git }
        params:
          NPM_TOKEN: ((npm_token))
          NPM_TAG: latest
        on_success:
          put: notify
          params:
            text_file: slack-message/publish
        on_failure:
          put: notify
          params:
            text_file: slack-message/publish

      - task: publish-docs
        file: main.git/concourse/tasks/publish-docs.yml
        input_mapping: { fauna-js-repository: main.git }

      - put: fauna-js-repository-docs
        params:
          repository: fauna-js-repository-updated-docs
