---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: shared-concourse-dind
    aws_access_key_id: ((prod-images-aws-access-key-id))
    aws_secret_access_key: ((prod-images-aws-secret-key))
    aws_region: us-east-2

params:
  FAUNA_ROOT_KEY:
  FAUNA_DOMAIN:
  FAUNA_SCHEME:
  FAUNA_PORT:

inputs:
  - name: fauna-js-repository

run:
  path: entrypoint.sh
  args:
    - bash
    - -ceu
    - |
      # start containers
      docker-compose -f fauna-js-repository/concourse/scripts/docker-compose-fauna.yml run node-lts
      docker-compose -f fauna-js-repository/concourse/scripts/docker-compose-fauna.yml run node-current
      # stop and remove containers
      docker-compose -f fauna-js-repository/concourse/scripts/docker-compose-fauna.yml down
      # remove volumes
      docker volume rm $(docker volume ls -q)
