---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: current

params:
  NPM_TOKEN:

inputs:
  - name: fauna-js-repository

outputs:
  - name: slack-message

run:
  path: ./fauna-js-repository/concourse/scripts/publish.sh
