---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: 22.10-alpine3.20

params:
  NPM_TOKEN:
  NPM_TAG:

inputs:
  - name: repo.git

outputs:
  - name: slack-message

run:
  path: ./repo.git/concourse/scripts/publish.sh
