---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: node
    tag: 22.10-alpine3.20

inputs:
  - name: fauna-js-repository
  - name: fauna-js-repository-docs

outputs:
  - name: fauna-js-repository-updated-docs

run:
  path: ./fauna-js-repository/concourse/scripts/publish_docs.sh
