name: Validate pull request (do not merge)

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize, ready_for_review]

jobs:
  do_not_merge-check:
    runs-on: ubuntu-latest
    steps:
      - name: Has tag
        if: github.base_ref == 'main' && contains( github.event.pull_request.labels.*.name, 'pr/do-not-merge')
        run: |
          echo "PR blocked: [tag: pr/do-not-merge]"
          exit 1

      - name: All good
        if: ${{ success() }}
        run: |
          echo "All good"
