name: Validate Driver

on:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["18", "20"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - name: Start FaunaDB service
        run: docker run --rm -d --name faunadb-local -p 8443:8443 -p 8084:8084 --mount type=bind,source="${{ github.workspace }}/docker/feature-flags.json",target=/etc/feature-flag-periodic.d/feature-flags.json fauna/faunadb

      - name: Start FaunaDB service alt port
        run: docker run --rm -d --name faunadb-local-alt-port -p 7443:8443 -p 7084:8084 fauna/faunadb

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"

      - name: Test
        uses: borales/actions-yarn@v4
        with:
          cmd: "test:ci"

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Jest Tests ${{ matrix.node }}
          path: reports/jest-*.xml
          reporter: jest-junit
