name: Validate Driver

on:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    services:
      core:
        image: fauna/faunadb:latest
        ports:
          - 8443:8443
        volumes:
          - ./docker/feature-flags.json:/etc/feature-flag-periodic.d/feature-flags.json
      alt_core:
        image: fauna/faunadb:latest
        ports:
          - 7443:8443
        volumes:
          - ./docker/feature-flags.json:/etc/feature-flag-periodic.d/feature-flags.json
    strategy:
      matrix:
        node: ["18", "20"]
      fail-fast: false
    steps:
      - name: FF Permission Fix
        run: sudo chown -R $USER:$USER /home/runner/work/fauna-js

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"

      - name: Test
        uses: borales/actions-yarn@v4
        with:
          cmd: "test:ci"

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Jest Tests ${{ matrix.node }}
          path: reports/jest-*.xml
          reporter: jest-junit
